PackageInformation data validation function
Lox-Solution/LoxServices pull request #121
Opened 2023-09-14 08:07 UTC by filipnd

Duplicates check foe inserts into PackageInformation

Tested it for a couple of cases in development database

2023-09-14 12:11 UTC, mathisbrrt approved these changes

2023-09-14 12:11 UTC, mathisbrrt commented on lox_services/persistence/database/datasets.py
> +    CarrierData = "CarrierData"
to remove

2023-09-15 07:20 UTC, mathisbrrt requested changes

2023-09-15 07:20 UTC, mathisbrrt commented on lox_services/persistence/database/insert.py
> +            dataframe = remove_duplicate_package_information(dataframe)
it would be nice to also add a quality_check function here 
checking at least null value + valid country code

2023-09-19 08:24 UTC, melvil-donnart approved these changes

2023-09-19 08:55 UTC, mathisbrrt approved these changes

2023-09-19 08:56 UTC, merged