Test coverage increase
Lox-Solution/LoxServices pull request #94
Opened 2023-07-06 16:02 UTC by melvil-donnart

2023-07-17 13:12 UTC, mathisbrrt requested changes

2023-07-17 13:12 UTC, mathisbrrt commented on lox_services/utils/Files/dummy.csv
> +this,is,a,test
this file can be move in the same folder than other test files

2023-07-17 13:12 UTC, mathisbrrt commented on tests/persistence/database/test_contants.py
typo in file name

2023-07-17 13:12 UTC, mathisbrrt commented on tests/proxy/test_brightdata.py
why everything is commented ?

2023-07-17 13:12 UTC, mathisbrrt commented on tests/utils/Files/test_image.png
I would put all the assets files in the same folder as we do it in main-algorithms

2023-07-17 13:28 UTC, melvil-donnart commented on tests/translation/test_use_locale.py
> +    # def test_download_locale(self):
Well, I comment it as the test runs locally but not on GitHub. Commenting it is the only way we can keep in a test file without making the tests crash

2023-07-18 06:31 UTC, mathisbrrt approved these changes

2023-07-18 06:34 UTC, merged